### ISSUE TITLE
Cannot SSH after compiled 

### ISSUE THREAD

**Issue by minasolution** [EmbER-Dev/EmbER#10]
Hi.

I've just built the latest commit of the repo and unfortunately cannot SSH into it.

Even though the password is set to "letmein" as in this file https://github.com/CoreTech-Development/buildroot-mx_linux/blob/2013.11-Amlogic_Gotham/configs/mx_linux_g18-mx2_newmtd_defconfig

FTP on root@IP on port 21 with password "letmein" works fine.
However if SSH on port 22, then this password does not work.

Please advise.

Many thanks.

**Comment by C-Prime90** [comment]
Please make sure that you have mkpasswd installed on your host machine.. It is apart of the whois package.
