### ISSUE TITLE
 LiveTV TVheadend hangs at fullscreen when changing channel

### ISSUE THREAD

**Issue by vvd214** [EmbER-Dev/EmbER#12]
My ATV1220 box with STVMX board running without any issues Frodo version. After upgrade to Gotham . It running ok but MyLivetv (tvheadend add-on) hangs at channel changes in full screen mode, if I stop and play other channel, it have no issues. In Frodo version changing channel in full screen mode work great. In xbmc log it show many message "ERROR:write header failed!" at end

**Comment by Stane1983** [comment]
I know about problem, need more time to investigate. Seems that AMLCodec can't be closed and reopened so fast. Probably we will have to put some delays in code.

**Comment by j1nx** [comment]
Indeed, Scott Davilla already has a hack in the ToFu fork.

**Comment by j1nx** [comment]
https://github.com/Pivosgroup/TOFU-XS-Android-TOFUApp/commit/57924313b44a7a7bf460fe8f32f3563fcdd14d0e

This one

**Comment by vvd214** [comment]
Thanks for response, is there any firmware file of Gotham's version I can try at the moment? cause i'm not good at compile from github to firmware file!!!

**Comment by C-Prime90** [comment]
Fix merged, https://github.com/CoreTech-Development/xbmc/commit/d437ece195b9238f11879b21dcfdeb2e6b8d5cc8

**Comment by vvd214** [comment]
Thanks for your fix, I'm waiting for new version with this fix, My box ATV1220 (G02REF board)(http://www.geniatech.com/pa/atv1220.asp) has DVB-T2 support, can you add support tvheadend server for that. If yes, will be great firmware for everyone. There is OPENELEC firmware for AMLogic support tvheadend server, but only for G18REF board.

**Comment by Stane1983** [comment]
I believe it's not going to be so easy... I can confirm that integrated tuners (Amlogic supported by drivers) are not recognized by tvheadend.

**Comment by vvd214** [comment]
Is there any Linux PVR backend server recognize TV tuners and stream TV on XBMC. can you help us? Onemore issues, I'm newbie  so can you help me how to buld firmware from this source in Ubuntu. I want to test the fix that croniccorey provide above, maybe I can help by report how it work?
