### ISSUE TITLE
Heads-up, the name "Ember" is already taken by an existing software related to Kodi/XBMC

### ISSUE THREAD

**Issue by Hedda** [EmbER-Dev/EmbER#16]
@croniccorey 

I would recommend that you choose a different name than "Ember" because it might confuse users since there already is a very popular software application called "Ember Media Manager" for XBMC/Kodi

http://kodi.wiki/view/Ember_Media_Manager
http://forum.kodi.tv/forumdisplay.php?fid=195
http://embermediamanager.org

**Comment by C-Prime90** [comment]
EmbER is a abbreviation of Embedded Entertainment ROM... At this point we cannot consider changing the name as logos have already bin made and alot of time is invested.

Thanks for input.

**Comment by Hedda** [comment]
OpenELEC is also "only" an abbreviation of Open Embedded Linux Entertainment Center, but no one ever says that, and most people probably don't even know that it is OpenELEC is an abbreviation for something much longer, never mind what that much longer name is.

Technically according to copyright law you do violate the trademark name of of Ember Media Manager even if your application is officially named Embedded Entertainment ROM but if outwards more known as its shorter abbreviation EmbER, and not by its full name (which you got to be honest with yourself, no one is going to use).

There is a whole thread on the Kodi/XBMC forum in which Nate explain the difference as far as copyright law goes http://forum.kodi.tv/showthread.php?tid=215856

Know that I have not any personal stake Ember Media Manager, and I'm only trying to warn you before in advance to save you unnecessary grief and future conflict with another team working on an application for XBMC/Kodi. 

No matter how you look at it, it is going to be much easier for you to change it now then it will be for you if you have to change it one year from now.

PS: Surprised that if you didn't know about Ember Media Manager, and if you did know about it then why would you still choose a name which abbreviation is the same when both are so closely related to XBMC/Kodi so everyone in that circle are going to be confused.

**Comment by Josh5** [comment]
Ember Media Manager is not a registered trademark as far as we are aware. So this is not an issue and there is no TM infringement here.
In any case, EmbER is clearly written as a abbreviation. I will endeavor to also design this clearly into the website.
