### ISSUE TITLE
Tronsmart ATV-106 (Prometheus)

### ISSUE THREAD

**Issue by rdscorreia74** [EmbER-Dev/EmbER#23]
Tonight I made a stupid mistake and tried to install EmbER using EXTRACTME_EmbER-Amlogic-G18REF_MX2REF-convert_v1.0.1
I extracted that to an sd card and then booted the tv box while pressing the internal reset button. Then I waited around 5 minutes but I never got any image on TV.
Then I tried going back to the original Android FW but the box keeps trying to flash the android firmware and restarts. It's on an endless loop.
I also tried to flash EXTRACTME_g18ref-mx2_Android_Revert but it also didn't work at all.
Is it really dead or can it still be brought back alive?

**Comment by C-Prime90** [comment]
Hi, 
Your box is not dead, you will need to create a recovery sdcard.
Send me a email at cronmod.dev@gmail.com and i can help.
