### ISSUE TITLE
add support for Meason 8

### ISSUE THREAD

**Issue by pigbait** [EmbER-Dev/EmbER#7]
Hello, was wondering if adding support for Meason 8 stuff would be possible,  tomatoe m8 square

**Comment by Stane1983** [comment]
Meson8 is WIP, partially working on my side on tronsmart vega like device. Not sure about shiningworth m8 (device you mentioned), will receive one soon then will see. I think corey have one.

**Comment by pigbait** [comment]
OK, great this is exciting, is this the best place to follow for news?

**Comment by C-Prime90** [comment]
Follow XDA and git it will be released once we belive it is ready

**Comment by pigbait** [comment]
Thanks Corey I'll check xda
