### ISSUE TITLE
libass compiling error.

### ISSUE THREAD

**Issue by hillyu** [EmbER-Dev/EmbER#9]
"make" can not pass configuration for libass because fribidi is missing.
manual build fribidi (make fribidi and then make) solves the problem. So I figured there might be some dependency issues.

**Comment by Stane1983** [comment]
libass makefile needs to be altered with:
LIBASS_DEPENDENCIES += fribidi

and Config.in of libass needs also be altered that it selects fribidi package (from my head):
config....
select BR2_PACKAGE_FRIBIDI
help
....

**Comment by C-Prime90** [comment]
Fixed by commit: e697f0de841fa7a50ef5a612e6523b2a53bc9809
